### PR TITLE
Update homepage visual design and add placeholder image for camps

### PR DESCRIPTION
**Pull request by wildal99**
# Update Homepage Visual Design
issue #22 / Sprint 2 PBI 4, Task 1.

1) Modify CampList.js to make the entire campCard a hyperlink.

2) Modify App.css to display up to 4 campgrounds per row (desktop), and fewer per row, as appropriate, for smaller screens, and display a placeholder image for each campground. It now displays up to 12 campgrounds per page, and center incomplete rows.

4) Modify App.css styling for the campCard and campCardContainer with appropriately sized, responsive padding.

5) Modify App.css to style the campground information to be black and not-underlined, even as a link.

6) Add spacing after the text search bar in App.css

### CODE REVIEW

**Comment by EvanMeyerEmich** [comment]
Tested on local machine, code works, looks good!

**Review by EvanMeyerEmich — APPROVED** [review]
Tested and works on my machine, everything looks good

**Comment by swill93** [comment]
Code looks good!

**Review by swill93 — APPROVED** [review]
Code looks good!

**Review by aeSzelag — COMMENTED** [review]
Code looks good to me.

**Review by aeSzelag — APPROVED** [review]
Looks good again

**Pull request merged**
