### PR TITLE
Clone from ec2 & implement search

### PR DESCRIPTION
**Pull request by EvanMeyerEmich**
This pull request includes the following changes:

# 1.  Cloned Repository from EC2:
    
   - Transferred the current version of the repository from the EC2 instance to my local machine.
    -   Created a new branch for this work to ensure smooth integration and prevent conflicts with the main branch.
# 2.  Search Feature by Keyword:
    
- Implemented a basic search functionality on the home page that allows users to search for campsites by entering keywords.
- The search is case-insensitive and searches across the campsite titles in real-time.
- Matching campsites are displayed in a grid format, maintaining the mobile-friendly layout.
# 3.  Tasks Completed:
    
- SSH-ed into the EC2 instance and cloned the latest version of the repo.
- Transferred the cloned repo files from EC2 to the local machine.
- Made local changes to implement the search feature.
- Pushed changes to the repository on a new branch.
- Tested the changes for functionality, ensuring the search results display correctly.

# Acceptance Criteria Met:
-   The repository is successfully cloned from the EC2 instance and transferred to the local machine.
-   A basic keyword search by title has been implemented and displays matching campsites in real-time.
-   The layout for search results is consistent with the existing grid (3 campsites across) and remains mobile-friendly.
-   If no campsites match the search, a message is displayed indicating no results.

**Next Steps:**

-   Review the search feature implementation and provide feedback.
-   Merge this branch into the main repository after approval.
- 
camp

### CODE REVIEW

**Comment by swill93** [comment]
Got it to work. Looks good to me!

**Comment by aeSzelag** [comment]
Thanks for fixing the .getignore. It looks good now!

**Comment by wildal99** [comment]
Looks good, and worked for me as well.

**Comment by sjiang1** [comment]
Grading Feedback:

Quality of Code: Good (15 points)
Participation in Code Review: Good (20 points)
Post-Review Changes: Needs Improvement (10 points): Unnecessary files should have been removed from the pull request as previously discussed.

Comments:
The format of the pull request description is excellent—clear and easy to follow.

Deductions:
(-5 points): The pull request is excessively large, containing more than 3,000 files.

Total Score:
15 + 20 + 10 - 5 = 40 points

**Pull request merged**
